server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway.server.webflux:
      discovery:
        locator:
          enabled: true
      routes:
        - id: commonlibrary-products
          uri: lb://commonlibrary
          predicates:
            - Path=/api/v1/products/**

        - id: commonlibrary-users
          uri: lb://commonlibrary
          predicates:
            - Path=/api/v1/users/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true