POST http://localhost:9090/api/v1/books
Content-Type: application/json

{
  "name": "System Design 3",
  "content": "Circuit Breaker",
  "price": 30000.00,
  "category": "SOFTWARE",
  "author": "Alex Xu"
}