POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "cache-connector",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "tasks.max": "1",
    "database.hostname": "postgres_db",
    "database.port": "5432",
    "database.user": "admin",
    "database.password": "admin",
    "database.dbname": "my_postgres_db",
    "plugin.name": "pgoutput",
    "slot.name": "debezium_book_slot",
    "publication.name": "cache_publication",
    "publication.autocreate.mode": "filtered",
    "schema.include.list": "public",
    "table.include.list": "public.books,public.products",
    "topic.prefix": "cdc",
    "poll.interval.ms": "100"
  }
}