spring:
  application:
    name: commonlibrary

  datasource:
    url: jdbc:postgresql://localhost:5432/my_postgres_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 9090

app:
  cache:
    enabled: true
    # Default configuration for all cache regions not explicitly declared.
    default-config:
      l1-initial-capacity: 100
      l1-maximum-size: 1000
      ttl-seconds: 300 # 5 minutes
      refresh-threshold-ratio: 0.8 # 80% TTL then refresh
      allow-null-values: true

    # Specific ThreadPool for Background Refresh Ahead
    refresh-thread-pool:
      core-pool-size: 5
      max-pool-size: 20
      queue-capacity: 500
      thread-name-prefix: "cache-refresh-"

    # Configuration for each of the region
    configs:
      products:
        l1-initial-capacity: 200
        l1-maximum-size: 5000
        ttl-seconds: 600
        refresh-threshold-ratio: 0.75
      users:
        l1-initial-capacity: 50
        l1-maximum-size: 500
        ttl-seconds: 120
        refresh-threshold-ratio: 0.8