spring:
  application:
    name: bookservice
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group
  datasource:
    url: jdbc:postgresql://localhost:5432/my_postgres_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 9091
